COMPAT: Delete the `GeoSeries.append` method (removed in pandas)
Similar to #3394

Calling `append` on a geoseries raises `AttributeError: 'super' object has no attribute 'append'`.

The upstream method has been removed in
[pandas 2.0](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#removal-of-prior-version-deprecations-changes),
the minimum supported version in pyproject.toml