Make explode() handle empty singular geom
```python
gs = gpd.GeoSeries(Point())
gs.explode()  # -> AttributeError: 'Point' object has no attribute 'geoms'
```

The above example throws an error on line 925, as an empty singular geometry object has `s.type == "GeometryCollection"`, but does not have the attribute `geoms`.

The proposed change checks if the geom is empty, and thus is passed on to the `else` statement on line 927.